apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
  namespace: roboshop
  labels:
    name: env
    project: production
spec:
  nodeSelector:
    env: production 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80