apiVersion: v1
kind: Pod
metadata:
  name: manual-scheduled-pod
  namespace: roboshop
  labels:
    name: nginx
    project: roboshop
spec:
  nodeSelector:
    env: production 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80