apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
  namespace: roboshop
  labels:
    name: env
    project: dev
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In 
            values:
            - production
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80